### ISSUE TITLE
race condition

### ISSUE THREAD

**Issue by cryptix** [cznic/ql#100]
Hi,

i started seeing weird behavior when I started hitting a ql db with lots of parallel read-only queries through an http interface. Something like reading a set of binary data fields from a table, transforming it somehow and serving that.

At first the system just stalled and stopped answering requests with very high cpu load. If it continues, answering requests, the db layer would return no rows for previously working IDs.

Or the db layer would return errors like this:
`row.Scan() failed: DecodeScalars: corrupted data @ 5002/16697`

I build the whole system with the race detector and got [lots of warnings](https://gist.githubusercontent.com/cryptix/6053755e86e8d208eed2/raw/5313c9ca3285c5aebc0c9699fa76a8032b8573f7/race.txt) when running this load and it also exits with a [panic](https://gist.githubusercontent.com/cryptix/6053755e86e8d208eed2/raw/2deea47e53b0f62ac1a786d90b55a763ef9a76dc/panic.txt) where it previously hung with high load.

I can't share the code directly but will try to extract the important parts and generalize them to a smaller reproducer. Please try to ignore the middleware. As a stopgap fix I'll just try to limit those queries.

**Comment by cznic** [comment]
Thanks a lot for the report and the links!

**Important:** Please let me know the exact QL revision the linked reports are based on if that's not the latest release (dc45f4323aeed12e777d2a032ec2e11eeb3c3676).

**Comment by cryptix** [comment]
Oh right.. This was reported running 329ce7f8930a8f3af240950cfe71dc0ffe714b43. I'll update and try again ASAP.

**Comment by cryptix** [comment]
master also shows this behavior, as well. I can reproduce the logs if you want the up2date stack traces.

**Comment by cznic** [comment]
Thanks a lot for the info. The existing links are fine, I think, now that I know the QL revision used. I hope to look into this issue tomorrow.

**Comment by cznic** [comment]
@cryptix Thanks again for the perfect report.

Please test the new version and please let me know if the changes do not work for you. In such case please reopen this issue.

Note:
```
Important: To make the fix work, the local copy of LLDB must be updated
as well. Suggested command:

        $ go get -u github.com/cznic/ql/...
```

**Comment by cryptix** [comment]
Thanks a ton for the fast fix!

The original query worked immediately.
For good measure, I also told the program to retrieve each of the parallel entries 20 times, which it also processed flawlessly and really fast, too.

**Comment by cznic** [comment]
Glad to hear it seems to work. If you would have a chance also to rerun your whole app with -race, as that was failing before, it would be nice to know if it's now ok - or not.

My trouble is that I was not able to quickly hack some code which fails for -race, so I'm still a bit unsure if the patch is complete.

**Comment by cryptix** [comment]
Oh, sure. I verified it with `-race` and it works, too. I tested `GOMAXPROCS=1` as well, to see if it can schedule the load, which it does!

(The whole thing takes 10 times as long to process with `-race` but I guess that's to be expected when your whole code base is riddled with counters ;) )

**Comment by cznic** [comment]
Good news, thank you ;-)
