### ISSUE TITLE
Object Database Support (e.g. OQL)

### ISSUE THREAD

**Issue by h12w** [cznic/ql#115]
Have you considered making ql an [Object Database](https://en.wikipedia.org/wiki/Object_database)?

As an embedded database in Golang, it will be far more valuable if it can store any hierarchical Go object and query on nested Go object fields rather than only primitive types and time types.

**Comment by cznic** [comment]
@h12w 

It's feasible and it's a hell of work. I'll probably never have that much available time to do it by myself. I can however provide help to anyone else wiling to write the code and tests.

I'll close the issue for now, but I'll happily reopen it would an volunteer leave a note here ;-)
