### ISSUE TITLE
Multi-process database access 

### ISSUE THREAD

**Issue by renfredxh** [cznic/ql#116]
Hi, I'm trying to use ql in a multi-process production environment (multiple servers using the same file system). I understand that ql is safe to use concurrently via multiple goroutines in the same process, but since the `OpenFile` method creates a lock on the `.db` file, it appears that more than one process cannot access a ql database at the same time. Is there any other way to accomplish this?

**Comment by omeid** [comment]
Have a database microservice that other servers talk to.

**Comment by cznic** [comment]
What @omeid said.

Alternatively, if the DB traffic is **really** low and no expensive, long running queries are required: Open the DB, do the short task, close it.
