### ISSUE TITLE
please tag formal releases

### ISSUE THREAD

**Issue by onlyjob** [cznic/ql#121]
Please consider assigning version numbers and tagging releases. Tags/releases
are quite useful for downstream package maintainers (in [Debian](http://debian.org) and other distributions) to export source tarballs, automatically track new releases and to declare dependencies between packages. Read more in the [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions).

Thank you.

See also https://en.wikipedia.org/wiki/Software_versioning

**Comment by cznic** [comment]
I'm not aware of a connection between ql and Debian. Is there any?

**Comment by onlyjob** [comment]
There will be. :)
We hope to package _rkt_ for Debian and _ql_ is a dependency.

**Comment by cznic** [comment]
Okay. I will first have to learn what to do and how to tell it to git. Have you by chance any pointers to some examples?

**Comment by onlyjob** [comment]
Thanks. Above mentioned wikipedia page describes versioning pretty well.
"Semantic Versioning" paragraph of the Docker documentation provides short summary:

  https://github.com/docker/docker/blob/master/VENDORING.md#semantic-versioning

See also http://semver.org/

Basically the idea is to tag release when you feel it will serve users better than head of "master" branch in regards to stability etc.
Release versions then could be used to define dependency on this package.

**Comment by cznic** [comment]
I think I understand semver. I have no idea about git tags/git version numbers ;-)

Anyway, thanks for your help, I will google what's needed.

**Comment by cznic** [comment]
There's now a [tag v1.0.0](https://github.com/cznic/ql/tree/v1.0.0). Hope it's what you wanted ;-)

**Comment by onlyjob** [comment]
Exactly. That is most helpful. Thank you so much. :)
