### ISSUE TITLE
vendoring github.com/camlistore/go4/lock

### ISSUE THREAD

**Issue by onlyjob** [cznic/ql#122]
Please consider vendoring `github.com/camlistore/go4/lock`.
As they [highlight in details](https://github.com/camlistore/go4#details), "_go4 makes no backwards compatibility promises. If you want to use go4, vendor it._".
That's also why it is not feasible to ship _go4_ as package to satisfy dependency of _cznic/ql_...
Vendoring _go4/lock_ should help to make _ql_ distribution comprehensive and reliable.
Thanks.

**Comment by cznic** [comment]
@onlyjob Alternatively, would it be ok for your purposes if I will fork go4/lock and import this fork?

**Comment by onlyjob** [comment]
I'm not sure... Embedded forks are usually a bad practice and camlistore/go4 is unpackageable mess... Is there are any better (maintained) alternatives to handle locks?
It should be OK to bundle fork but it means extra maintenance effort to sync with upstream and forward your improvements...

**Comment by cznic** [comment]
Okay, I will vendor the package.

**Comment by onlyjob** [comment]
Thank you. :)

**Comment by cznic** [comment]
Please checkout and test branch `issue122` and let me know if fit for merging.

Note: `vendored` in the path is not a typo, I want to avoid any vendoring mechanism handling specially the `vendor` subdirectory.

**Comment by cznic** [comment]
@onlyjob Gentle ping.

**Comment by onlyjob** [comment]
Sorry for delay. I have to deal with some other priorities for now... I'll get back to it as soon as I can...

**Comment by cznic** [comment]
No problem, no hurry ;-)

**Comment by onlyjob** [comment]
Looks good, thank you. It might be a good idea to vendor `github.com/cznic/exp` as well because it is considered to be unstable just like `camlistore/go4`?

**Comment by cznic** [comment]
Thanks for looking into this. 

>  It might be a good idea to vendor github.com/cznic/exp as well because it is considered to be unstable just like camlistore/go4?

Will do.

**Comment by onlyjob** [comment]
Thank you.

**Comment by cznic** [comment]
PTAL

**Comment by onlyjob** [comment]
?

**Comment by xiam** [comment]
I was having this problem:

```
go get -v github.com/cznic/ql/ql
github.com/cznic/ql (download)
github.com/camlistore/go4 (download)
package github.com/cznic/ql/ql
	imports github.com/camlistore/go4/lock
	imports github.com/camlistore/go4/lock
	imports github.com/camlistore/go4/lock: code in directory /home/travis/gopath/src/github.com/camlistore/go4/lock expects import "go4.org/lock"
```

But I guess that is related to this other one, right?

**Comment by cznic** [comment]
@onlyjob 

> ?

Please elaborate, I'm slow today ;-)

**Comment by onlyjob** [comment]
I was hoping you can elaborate on "PTAL". What is it stand for?

**Comment by cznic** [comment]
My apologies for not being clear!

It means: Please Také Another Look.

**Comment by onlyjob** [comment]
Looks good, thank you. :)
