### ISSUE TITLE
Unable to compile without cgo using go 1.7 on Windows 8.1

### ISSUE THREAD

**Issue by sqdk** [cznic/ql#133]
Hi everyone,

I am having some trouble building ql without cgo.

I am using go 1.7 on Windows 8.1.

I tried cleaning my directories, and following the guide here: https://godoc.org/github.com/cznic/ql#hdr-Building_non_CGO_QL to build it, but zappy is complaining that `gcc` is not in my path.

These are the steps that i have tried:

```
# Clean directories as an attempt to start from a clean slate.
$ rm -rf $GOPATH/pkg/windows_amd64/*
$ rm -rf $GOPATH/src/github.com/cznic/*

$ go install -tags purego github.com/cznic/zappy
$ go get -tags purego github.com/cznic/ql
$ go build
# github.com/cznic/zappy
exec: "gcc": executable file not found in %PATH%
```

If it matters, i am running the commands through git-bash with a default setup.

Are the docs out of date? Or am i missing something?

Thanks a lot. Great project that i am looking forward to using.

**Comment by cznic** [comment]
Can you please try `go build -tags purego`?

**Comment by sqdk** [comment]
Thanks @cznic, that worked perfect. So I was missing something.

Thanks a lot!
