### ISSUE TITLE
Record size limit for file backed db

### ISSUE THREAD

**Issue by fatihcode** [cznic/ql#135]
@cznic : Can you give some details about record size limit?

```go
// OpenFile returns a DB backed by a named file. The back end limits the size
// of a record to about 64 kB.
func OpenFile(name string, opt *Options) (db *DB, err error) {
}
```
Why 65kb and can it be changed?

**Comment by cznic** [comment]
The limitation comes from the underlying [engine](https://github.com/cznic/lldb). It's a bit more than 64kB for the whole record and, actually, 64kB-1 for strings.

It cannot be changed ATM. The limitation can be to some extent bypassed using blobs as they do not have that limit.

```bash
$ ql 'drop table if exists t'
$ ql 'create table t (s string)'
$ ql 'insert into t values (__testString(65535))'
$ ql 'select len(s) from t'
65535
$ ql 'insert into t values (__testString(65536))'
2016/09/10 11:24:17 EncodeScalars: cannot encode string of length 65536 (limit 65536): BEGIN TRANSACTION;
$ ql 'drop table t'
$ ql 'create table t (s blob)'
$ ql 'insert into t values (__testBlob(100000))'
$ ql 'select len(string(s)) from t'
100000
$

```

Note that one can freely [convert](https://godoc.org/github.com/cznic/ql#hdr-Conversions_to_and_from_a_string_type) between a blob (`[]byte`) and a `string`. Also, the same conversion is possible in Go code.

**Comment by fatihcode** [comment]
Thank you for the details. I was looking for `blob` thing 👍
