### ISSUE TITLE
mobile testing

### ISSUE THREAD

**Issue by joeblew99** [cznic/ql#139]
Has anyone had any experience with compiling this to Android or IOS using the standard "gomobile build", as opposed to using the "gomobile bind" ?

**Comment by cznic** [comment]
Possibly related #132 .

**Comment by joeblew99** [comment]
yes it will be.

on android the file to write to is the same as where the apk is installed to on the disk.

So the code needs to simple ask where its running and it can write in the same place.

Does this help ?

**Comment by cznic** [comment]
The `/tmp` is not hardcoded, it asks `ioutil.TempFile` in [`file.go#88`](https://github.com/cznic/ql/blob/c81467d34c630800dd4ba81033e234a8159ff2e3/file.go#L99), so the outcome depends on what `gomobile` sets as the `GOOS`. From #132 it seems the setting is probably not the one informing `ioutil.TempFile` to return the proper path. That's about all I know about this. Still hoping @gedw99 will report back.

> So the code needs to simple ask where its running and it can write in the same place.

I'm afraid that's not what users do expect on desktop systems. Using a proper temp file path ensures the file is deleted, if accidentally left over, at least on next reboot/cleanup/whatever event it takes to swipe the temp folder content.

However, if we understand the issue properly, we can switch on GOOS in QL to bypass #132, but there it's reported setting `GOOS` to `android`, for example, breaks the build. So I really don't know what's the proper fix.

**Comment by joeblew99** [comment]
ok i think i get what your saying.

i need to try this out with a gomobile build. I will do that next week i hope.
then i can make a PR ..

**Comment by joeblew99** [comment]
this works for me on android.
i am NOT making an aar anymore, and so compiling with GOOS=android works.

Sorry about the confusion on this one, and thanks for the help.
