### ISSUE TITLE
RFE: "free-space headroom" or "spare-block pool"

### ISSUE THREAD

**Issue by squeed** [cznic/ql#140]
Apologies in advance if this should be filed against lldb.

We use ql (and therefore lldb) as part of rkt's [image store](https://github.com/coreos/rkt/tree/master/store). The details aren't super important, but we have a CAS blobstore for container images and a small ql db for metadata.

One problem we have is if the data partition fills up (which is common enough, since by default it's on `/var`), then our users can't delete images ([issue](coreos/rkt#2782)). This is because we need to remove all references to a blob in the metadata before it's safe to delete the blob itself. However, since the partition is full, commits to the ql db fail.

These are not large commits - deleting fewer than 10 narrow rows - so the actual disk space requirements are very small. So, it would be nice if there was some kind of configurable headroom, especially for the WAL, so that we could make our small change, commit, and free up lots of disk space.

So, this is an RFE for a configurable free-space headroom. Writes that dip in to the headroom should not fail.

**Comment by cznic** [comment]
@squeed 
Probably feasible, not sure how much complicated it could be, will have to investigate.

Meanwhile, please suggest the API for the knob(s). (Or perhaps some pragma-like QL command?)

**Comment by squeed** [comment]
One suggestion:
```go
db, err := sql.Open("ql", "file://ql.db?headroom=2048")
```

It could be added to the Options parameter to `OpenFile`

**Comment by cznic** [comment]
Looks ok.

**Comment by cznic** [comment]
@squeed 

Please test https://github.com/cznic/ql/commit/4ba878e346dd3c437c4a5cba5f6260422e3429cd with https://github.com/cznic/lldb/commit/1402951a9788f1b6bf2ef1b21ec8ac127d4675bc and let me please know the outcome. Thank you.

**Comment by cznic** [comment]
References updates coreos/rkt#2782.

**Comment by squeed** [comment]
Wow, thanks!
However, it's not working for me. I can reproduce with a small patch to the `ql` command:
```diff
diff --git a/ql/main.go b/ql/main.go
index 568fd70..df80fe1 100644
--- a/ql/main.go
+++ b/ql/main.go
@@ -99,7 +99,7 @@ func do() (err error) {
                }()
        }
 
-       db, err := ql.OpenFile(*oDB, &ql.Options{CanCreate: true})
+       db, err := ql.OpenFile(*oDB, &ql.Options{CanCreate: true, Headroom: 1})
        if err != nil {
                return err
        }
```

Then, when I create and then re-open a DB file, it fails:

```
$ echo "CREATE TABLE test (col int)" | ./ql
$ echo "SELECT * from test" | ./ql
2016/10/31 14:09:27 (file-001) non empty WAL file .34a8b4c1ad933745146fdbfef3073706ee571625 exists
```

If I don't pass the headroom parameter, it works.

**Comment by cznic** [comment]
@squeed 

```bash
$ ql 'create table t(c int)'
$ ql 'select * from t'
$ ql 'insert into t values(42)'
$ ql 'select * from t'
42
$ 
```

Here it seems to work, PTAL using ql@https://github.com/cznic/ql/commit/df4ef4823d9b9bf2a3f27291d5e31fd6aa30c97e with https://github.com/cznic/lldb/commit/04c9cd7614fd552d7b237f010734010f44b9507d, thank you.

**Comment by squeed** [comment]
So, testing it with a full directory gives an interesting result: an error code is returned, but the write succeeds:

```
sudo mount -t tmpfs -o size=2M tmpfs tmp && cd tmp
$ ql 'create table t(c int)'
$ ql 'insert into t values(42)'
$ dd if=/dev/urandom of=a.txt bs=4096 count=1000
$ ../ql 'delete from t'                         
2016/10/31 17:55:46 write ql.db: no space left on device: BEGIN TRANSACTION;
$ echo $?
1
$ ../ql 'select * from t' 
(no records returned)
```

So, the commit should not return an error. But getting there, thank you!

**Comment by cznic** [comment]
Thanks for your patience. FYI: I am not yet able to find where the error message comes from (using `grep -nwr write *` in `cznic{ql,lldb,internal}`) ???

**Comment by jonboulle** [comment]
@cqnic that is probably coming from the go stdlib's file write path

**Comment by cznic** [comment]
@jonboulle 

Thanks for the hint, I think you're right.

**Comment by cznic** [comment]
@squeed 

FTR: Thanks for the test case, I can reproduce:

```bash
jnml@4670:~/tmp/ql$ cat test.sh 
# Set headroom in the QL tool to 16kB.

set -e
set -v
go install -v github.com/cznic/ql/ql
sudo umount tmp || true
rm -rf tmp
mkdir tmp
sudo mount -t tmpfs -o size=2M tmpfs tmp
cd tmp
ql 'create table t(c int)'
ql 'insert into t values(42)'
dd if=/dev/urandom of=a.txt bs=4096 count=1000 || true
ls -la
df -h .
ql 'delete from t' || true
ql 'select * from t'
cd ..
sudo umount tmp
jnml@4670:~/tmp/ql$ ./test.sh 
go install -v github.com/cznic/ql/ql
sudo umount tmp || true
umount: tmp: not mounted
rm -rf tmp
mkdir tmp
sudo mount -t tmpfs -o size=2M tmpfs tmp
cd tmp
/home/jnml/tmp/ql/tmp
ql 'create table t(c int)'
ql 'insert into t values(42)'
dd if=/dev/urandom of=a.txt bs=4096 count=1000 || true
dd: error writing 'a.txt': No space left on device
509+0 records in
508+0 records out
2080768 bytes (2,1 MB, 2,0 MiB) copied, 0,128175 s, 16,2 MB/s
ls -la
total 2052
drwxrwxrwt 2 root root     100 lis    1 13:28 .
drwxrwxr-x 3 jnml jnml    4096 lis    1 13:28 ..
-rw-rw-r-- 1 jnml jnml   16384 lis    1 13:28 .34a8b4c1ad933745146fdbfef3073706ee571625
-rw-rw-r-- 1 jnml jnml 2080768 lis    1 13:28 a.txt
-rw-rw-r-- 1 jnml jnml     208 lis    1 13:28 ql.db
df -h .
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           2,0M  2,0M     0 100% /home/jnml/tmp/ql/tmp
ql 'delete from t' || true
2016/11/01 13:28:25 write ql.db: no space left on device: BEGIN TRANSACTION;
ql 'select * from t'
cd ..
sudo umount tmp
jnml@4670:~/tmp/ql$ 
```

**Comment by cznic** [comment]
@squeed PTAL with https://github.com/cznic/lldb/commit/27efa11da9badd2caae6fde67b4530c7e57d8d96, thank you.

**Comment by squeed** [comment]
@cznic this works perfectly, thank you!

**Comment by squeed** [comment]
Would it be possible to cut a release of ql that includes this? Thanks!

**Comment by cznic** [comment]
Sure. Will just update docs first.

**Comment by cznic** [comment]
@squeed Done: https://github.com/cznic/ql/releases/tag/v1.1.0
