### ISSUE TITLE
go1.8: support for additional features

### ISSUE THREAD

**Issue by kardianos** [cznic/ql#141]
Many new important features will land in go1.8. Please see document:
https://docs.google.com/document/d/1F778e7ZSNiSmbju3jsEWzShcb8lIO4kDyfKDNm4PNd8/edit?usp=sharing for the full list.

Because these features are new we want drivers to implement them before they are released. Ideally they should be implemented by 2016-12-12 to allow for any driver provided feedback from implementation if necessary.

**Comment by cznic** [comment]
Thanks for the head-up. Was on my radar already, but it's good to have a tracking issue for it. Thank you.

**Comment by gernest** [comment]
@cznic  I would like to take this one. If you have any advice it will be great. I will first need to introduce `context.Context` which means somehow we need to figure out to cancel query execution. 

My first sweep of the code wasn't that successful.

**Comment by cznic** [comment]
It's yours ;-)

Please isolate the Go 1.8 specific features in a separate file guarded by `//+build go1.8` to keep support of older Go versions.
