### ISSUE TITLE
Open or Create database

### ISSUE THREAD

**Issue by TheMrViper** [cznic/ql#142]
Hi. Have problem with **ql**.

When i try open db: 

> sql.Open("ql", "test.db") - got error Invalid db name
> sql.Open("ql", "./test.db") - premission denied

Please make opening more simple, you dont need parse file path like uri. Look to [buntdb](https://github.com/tidwall/buntdb).

> buntdb.Open("test.db") - open file
> buntdb.Open(":memory:") - in memory

**Comment by cznic** [comment]
@TheMrViper Please test https://github.com/cznic/ql/commit/3135d11835bf2f84cc2f9080c5eb5eda4fdf6083 and please let me know if it fixes the issue for you. Thank you.

**Comment by cznic** [comment]
@TheMrViper I'm pushing the fix b/c it's a critical bug. Feedback would be welcome anyway. Thank you for the report.

**Comment by TheMrViper** [comment]
Thank you. Now it work fine.

**Comment by cznic** [comment]
Glad to hear that and thanks for the feedback.
