### ISSUE TITLE
Zero-size WAL files are not removed on exit

### ISSUE THREAD

**Issue by vkryukov** [cznic/ql#143]
Hello there,

QL is great, and I can use it without any GCC dependencies. I noticed that I have several .dot files being created in the same folder where I run a program that uses QL library (see below), but they are not removed after the program exists, and I do call `defer _DB.close()` in my main. I think these files might be related to QL locking mechanism.
```
.34a8b4c1ad933745146fdbfef3073706ee571625
.8750451be59059bc01b258e5315f2e7aa75d4350
.f630cc97640448d8f823924a7df3ca00e4d9e53b
```

Is it the intended behavior, or do I need to do anything in my code to clean things up?

**Comment by cznic** [comment]
When a database is in use, two .files are used, a lock file and and a [WAL](https://en.wikipedia.org/wiki/Write-ahead_logging) file. If the database is cleanly closed, the lock file should be removed, while the WAL file is left there. It serves when later reopening the database to distinguish between a clean shutdown (WAL is zero sized) and a application crash while the database was being updated. In the later case the WAL contains database recovery data.

QL assumes missing WAL file is the same as a zero sized one.

Can you please investigate if the leftover .files are WALs or lock files?

**Comment by vkryukov** [comment]
It's a WAL name. I checked it by manually applying `walName` from https://github.com/cznic/ql/blob/master/file.go#L1094 and `lockName` from https://github.com/cznic/ql/blob/master/file.go#L1087 to my database name.

I still don't understand why WAL file is left over as https://github.com/cznic/ql/blob/master/file.go#L424 seem to remove it during a clean close?

**Comment by vkryukov** [comment]
But since it's a WAL file, from your description above sounds like that it is left there by design, so not really an issue? If that's the case, please feel free to close this ticket.

**Comment by cznic** [comment]
> I still don't understand why WAL file is left over as https://github.com/cznic/ql/blob/master/file.go#L424 seem to remove it during a clean close?

That line remove the WAL file when opening a database fails when a WAL file has already been created. IIRC, a clean shutdown does not normally remove the WAL file. I guess it's possible to add a field to the [Options](https://godoc.org/github.com/cznic/ql#Options) asking to remove the WAL file on clean shutdown.

> But since it's a WAL file, from your description above sounds like that it is left there by design, so not really an issue? If that's the case, please feel free to close this ticket.

I think it's not in the 'bug' category, but you're not the first user to ask about this design choice so I guess the above mentioned option could be useful. Do you want to send a PR for review? ;-)

**Comment by vkryukov** [comment]
Re: PR - since the information that we want a zero-sized WAL file be removed on closure needs to persist somewhere until `DB.Close()` is called (right?), would you recommend storing it in `DB` or the underlying `file`?

**Comment by vkryukov** [comment]
Well, I guess it should be stored in `file` as `DB` abstracts away the underlying storage?

**Comment by cznic** [comment]
I think you're right, `file` seems the be the proper place. In any case, it will be a private field, so if it may later turn out it needs to belong elsewhere, it should be possible to adjust without breaking the API.

**Comment by vkryukov** [comment]
I ran the tests before making any changes, and it produces some errors - I assume they are all known issues (at least on Windows)?

```
$ go test -tags purego
--- FAIL: TestMemStorage (0.76s)
        storage_test.go:485: FAIL: test # 300
                -- 300
                BEGIN TRANSACTION;
                        CREATE TABLE t(c blob);
                        INSERT INTO t VALUES (blob(`
                0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
                `));
                COMMIT;
                SELECT * FROM t;

                ---- g
                "c"
                [[13 10 48 49 50 51 52 53 54 55 56 57 97 98 99 100 101 102 48 49 50 51 52 53 54 55 56 57 97 98 99 10                0 101 102 48 49 50 51 52 53 54 55 56 57 97 98 99 100 101 102 48 49 50 51 52 53 54 55 56 57 97 98 99 100 101 102 13 1                0]]
                ---- e
                "c"
                [[10 48 49 50 51 52 53 54 55 56 57 97 98 99 100 101 102 48 49 50 51 52 53 54 55 56 57 97 98 99 100 1                01 102 48 49 50 51 52 53 54 55 56 57 97 98 99 100 101 102 48 49 50 51 52 53 54 55 56 57 97 98 99 100 101 102 10]]
                ----
--- FAIL: TestFileStorage (8.31s)
        storage_test.go:485: FAIL: test # 300
                -- 300
                BEGIN TRANSACTION;
                        CREATE TABLE t(c blob);
                        INSERT INTO t VALUES (blob(`
                0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
                `));
                COMMIT;
                SELECT * FROM t;

                ---- g
                "c"
                [[13 10 48 49 50 51 52 53 54 55 56 57 97 98 99 100 101 102 48 49 50 51 52 53 54 55 56 57 97 98 99 10                0 101 102 48 49 50 51 52 53 54 55 56 57 97 98 99 100 101 102 48 49 50 51 52 53 54 55 56 57 97 98 99 100 101 102 13 1                0]]
                ---- e
                "c"
                [[10 48 49 50 51 52 53 54 55 56 57 97 98 99 100 101 102 48 49 50 51 52 53 54 55 56 57 97 98 99 100 1                01 102 48 49 50 51 52 53 54 55 56 57 97 98 99 100 101 102 48 49 50 51 52 53 54 55 56 57 97 98 99 100 101 102 10]]
                ----
--- FAIL: TestOSFileStorage (8.25s)
        storage_test.go:485: FAIL: test # 300
                -- 300
                BEGIN TRANSACTION;
                        CREATE TABLE t(c blob);
                        INSERT INTO t VALUES (blob(`
                0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
                `));
                COMMIT;
                SELECT * FROM t;

                ---- g
                "c"
                [[13 10 48 49 50 51 52 53 54 55 56 57 97 98 99 100 101 102 48 49 50 51 52 53 54 55 56 57 97 98 99 100 101 102 48 49 50 51 52 53 54 55 56 57 97 98 99 100 101 102 48 49 50 51 52 53 54 55 56 57 97 98 99 100 101 102 13 10]]
                ---- e
                "c"
                [[10 48 49 50 51 52 53 54 55 56 57 97 98 99 100 101 102 48 49 50 51 52 53 54 55 56 57 97 98 99 100 101 102 48 49 50 51 52 53 54 55 56 57 97 98 99 100 101 102 48 49 50 51 52 53 54 55 56 57 97 98 99 100 101 102 10]]
                ----
--- FAIL: TestIssue28 (0.01s)
        all_test.go:2018: parse file://C:\Users\KRYUKO~1\AppData\Local\Temp\ql-test-657924690\ql.db: invalid character "\\" in host name
--- FAIL: TestIssue56 (0.01s)
        all_test.go:2241: parse file://C:\Users\KRYUKO~1\AppData\Local\Temp\ql-test-079864660\test.db: invalid character "\\" in host name
--- FAIL: TestIssue66FileDriver (0.01s)
        all_test.go:2537: parse file://C:\Users\KRYUKO~1\AppData\Local\Temp\ql-test-766154662\TestIssue66MemDriver: invalid character "\\" in host name
--- FAIL: TestIssue73 (0.01s)
        all_test.go:2621: Call to db.Begin()
        all_test.go:2623: db.Begin:  parse file://C:\Users\KRYUKO~1\AppData\Local\Temp\ql-test-812338893\test.db: invalid character "\\" in host name
--- FAIL: TestHTTP (0.00s)
        httpfs_test.go:123: file does not exist
FAIL
exit status 1
FAIL    github.com/vkryukov/ql  19.397s
```

**Comment by vkryukov** [comment]
Looking at it more closely, the `13 10` vs. `10` difference is very telling - looks like EOL difference between the platforms.

**Comment by cznic** [comment]
No, I was not aware of those errors - I do not normally use Windows. Tests and/or other things need to be fixed. Please fill a separate issue for that, thank you.

**Comment by vkryukov** [comment]
Since the above errors all seem to be related to Windows idiosyncrasies vs. Unix (EOL, slash/backslash in file names), I have sent you a pull request for this one anyways and will open a separate issue for failing tests.

**Comment by cznic** [comment]
Thanks a lot! I will review all patch(es) you've sent later today, I hope (woke up today with a flu).

**Comment by cznic** [comment]
Reviewed this one, it LGTM, but it needs a simple test. Maybe it's included in the other patches which I haven't seen yet.
