### ISSUE TITLE
autoincrement field property?

### ISSUE THREAD

**Issue by jamesrr39** [cznic/ql#148]
Hi, nice project. Is there a way to have any kind of AUTOINCREMENT property on a field? I can't find anything in godoc or google search. The use case would be generating an artificial ID.

I've tried these without success:

errors on insert (unknown field AUTOINCREMENT: BEGIN TRANSACTION;):

    CREATE TABLE x (
        y INT AUTOINCREMENT,
        z STRING
    );

errors on table creation (expected CREATE INDEX optional UNIQUE clause or one of [INDEX, TABLE, UNIQUE]):

    CREATE TABLE x (
        y INT
    );
    CREATE PRIMARY KEY primary_idx_x_y ON x (y);

corresponding SQLite feature webpage: http://sqlite.org/autoinc.html

**Comment by cznic** [comment]
If you need sequential numbering provided by SQLITE's `AUTOINCREMENT` then no, QL does not have that feature. It could be implemented, of course.

However, if you need just a unique number, like SQLITE's `ROWID` then you can use [`id()`](https://godoc.org/github.com/cznic/ql#hdr-Record_id). It can be used in [`CREATE INDEX`](https://godoc.org/github.com/cznic/ql#hdr-CREATE_INDEX) as well. Would that be enough in your use case?

Performance hint: Using `id()` should be faster as it just provides a value every record in the DB already has. `AUTOINCREMENT`, OTOH, would make inserts somewhat slower.

**Comment by cznic** [comment]
@jamesrr39  FTR: The QL version in this case would be something like

```sql
CREATE TABLE x (
        z STRING
);
CREATE INDEX primary_idx_x ON x (id());
```

**Comment by jamesrr39** [comment]
thanks - `CREATE INDEX primary_idx_x ON x (id());` and `id()/Id()` turned out to be what I needed.
