### ISSUE TITLE
`commit` cannot be used as an identifier

### ISSUE THREAD

**Issue by boyvanduuren** [cznic/ql#152]
A column cannot be called `commit`, even though it's not a reserved keyword [according to the documentation](https://godoc.org/github.com/cznic/ql#hdr-Keywords).

```
ql "CREATE TABLE foo (commit string)"
2017/03/02 20:33:34 BEGIN TRANSACTION; CREATE TABLE foo (commit string); COMMIT;
2017/03/02 20:33:34 1:38 unexpected COMMIT, expected table column definition or identifier
```

**Comment by cznic** [comment]
@boyvanduuren The list of reserved words at the link you've provided unfortunately misses `commit`, even though it [actually is](https://github.com/cznic/ql/blob/77151e6627d3f052ab9c993a16d95942b4922ddc/scanner.l#L148) a reserved word.

Would you like to send a PR to fix the documentation?

**Comment by boyvanduuren** [comment]
Just created the PR: #153.

**Comment by cznic** [comment]
Thanks, please check the comment [there](https://github.com/cznic/ql/pull/153#issuecomment-283926808).
