### ISSUE TITLE
Compile without CGO?

### ISSUE THREAD

**Issue by mbergin** [cznic/ql#154]
I was looking for a pure Go implementation of an embedded SQL database since mattn/go-sqlite3 requires CGO. This project looks perfect.

However I tried to install the package on Windows where I don't have gcc, and we seem to have a CGO dependency via cznic/zappy:

```
>go get github.com/cznic/ql
# github.com/cznic/zappy
exec: "gcc": executable file not found in %PATH%
```

I tried setting `CGO_ENABLED=0` but this doesn't seem to do anything. Perhaps I need to rebuild the standard library?

**Comment by cznic** [comment]
@mbergin Plase see the [documentation](https://godoc.org/github.com/cznic/ql#hdr-Building_non_CGO_QL) for building QL without CGO.

**Comment by mbergin** [comment]
Oops. Thank you.
