### ISSUE TITLE
How do i use dummy table in ql?

### ISSUE THREAD

**Issue by gernest** [cznic/ql#155]
Hi,

I'm not well versed in SQL and ql. I'm adding ql support to one object relational mapper. When I was implementing many to many support I came across this query.

```sql
INSERT INTO blog_tags 
            (blog_id, 
             blog_locale, 
             tag_id, 
             tag_locale) 
SELECT $1, 
       $2, 
       $3, 
       $4 
WHERE  NOT EXISTS (SELECT * 
                   FROM   blog_tags 
                   WHERE  blog_id = $1 
                          AND blog_locale = $2 
                          AND tag_id = $3 
                          AND tag_locale = $4) 
```

A quick google and some tinkering I came across the dummy table thing. This query works fine in postgres but it does not work in ql. I was wondering if there is a way I can write a query like this.

Thanks

**Comment by cznic** [comment]
@gernest So far I'm not sure I understand what is the question. Assuming the query above does not work: What's failing and/or what feature is needed/missing? I'm unfortunately not able to infer that from "_the dummy table thing_". Please explain it a bit more or provide additional context/reproduction case etc., thank you.

**Comment by gernest** [comment]
@cznic 

In the query  portion above 

```sql
SELECT $1, 
       $2, 
       $3, 
       $4 
WHERE  ...
```

We are selecting values $1,$2,$3    from nothing.  postgresql supports that. And from stackoverflow they say mysql support by having `DUAL` which will be something like.

```sql
SELECT $1, 
       $2, 
       $3, 
       $4 
 FROM DUAL WHERE  ...
```

In ql I get this error 
```
 unexpected WHERE, expected field expression optional AS clause or logical or operator or one of [',', AS, FROM, OR, ||]
```

**Comment by gernest** [comment]
Just to be clear. I'm not an expert in SQL. I just want to be able to use the object relational mapper with ql without worrying about query building. So, I might be missing something here.

**Comment by gernest** [comment]
I have tried to reproduce it.

postgres
```
postgres=# select 30 where 1=1;
 ?column? 
----------
       30
(1 row)
```

ql
```
$ ql 'select 10 where 1=1'
2017/03/26 02:42:18 BEGIN TRANSACTION; select 10 where 1=1; COMMIT;
2017/03/26 02:42:18 1:30 unexpected WHERE, expected field expression optional AS clause or logical or operator or one of [',', AS, FROM, OR, ||]
```

Is there any way I can have the same outcome in ql as in the postgres example?

**Comment by cznic** [comment]
Thank you very much for the added information.

> Is there any way I can have the same outcome in ql as in the postgres example?

Right now it seems feasible to me, but I have to look into it more thoroughly. I will investigate.

**Comment by gernest** [comment]
My pleasure. 

Thanks for the amazing work.  And please don't don't forget to ping me when something comes up from your investigation as I have to wait  for your insight before I opt to  look for a work around.

**Comment by cznic** [comment]
@gernest I've tweaked the grammar to accept all the new constructs (missing `FROM`, `WHERE [ NOT ] EXISTS ( SELECT ...)` as well as capturing the added parsing values to the respective structs.

The rest is just a question of a non-trivial amount of work.

- Tweak all places which assume the `selectStmt.from.sources` are always non-nil and change the implementation to cope with it.
- Implement the new `[ NOT ] EXISTS` predicate of the `WHERE` clause.
- Adjust the planner to optimize all of the above.
- Adjust the documentation accordingly.

I can implement this, but it may take months for me to do that. If you would like to give it a try by yourself, I can offer guidance and code reviews. It would not be easy, it would probably not make it happen any sooner - but you will learn a lot about `ql`, which you might be interested in. WDYT?

**Comment by gernest** [comment]
@cznic cool!

I will be more than happy to try this. So, maybe a hint on where to start will be appreciated.

**Comment by cznic** [comment]
As a starter, already failing code paths can be used to indicate the "must" places in need of change. Consider

```bash
jnml@4670:~/src/github.com/cznic/ql$ git branch 
  issue141
  issue142
  issue151
* issue155
  master
jnml@4670:~/src/github.com/cznic/ql$ go test
--- FAIL: TestMemStorage (0.51s)
	storage_test.go:364: recreated source does not compile: 1:1 unexpected '%!'(MISSING), expected Start or one of [$end, ';', ALTER, BEGIN, COMMIT, CREATE, DELETE, DROP, EXPLAIN, INSERT, ROLLBACK, SELECT, TRUNCATE, UPDATE, parse expression prefix]
		---- orig
		-- 1347 // https://github.com/cznic/ql/issues/155
		SELECT 42;
		
		---- recreated
		%!s(PANIC=runtime error: slice bounds out of range)
	storage_test.go:356: 1348 error: internal error 052
--- FAIL: TestFileStorage (1.29s)
	storage_test.go:364: recreated source does not compile: 1:1 unexpected '%!'(MISSING), expected Start or one of [$end, ';', ALTER, BEGIN, COMMIT, CREATE, DELETE, DROP, EXPLAIN, INSERT, ROLLBACK, SELECT, TRUNCATE, UPDATE, parse expression prefix]
		---- orig
		-- 1347 // https://github.com/cznic/ql/issues/155
		SELECT 42;
		
		---- recreated
		%!s(PANIC=runtime error: slice bounds out of range)
	storage_test.go:356: 1348 error: internal error 052
--- FAIL: TestOSFileStorage (1.29s)
	storage_test.go:364: recreated source does not compile: 1:1 unexpected '%!'(MISSING), expected Start or one of [$end, ';', ALTER, BEGIN, COMMIT, CREATE, DELETE, DROP, EXPLAIN, INSERT, ROLLBACK, SELECT, TRUNCATE, UPDATE, parse expression prefix]
		---- orig
		-- 1347 // https://github.com/cznic/ql/issues/155
		SELECT 42;
		
		---- recreated
		%!s(PANIC=runtime error: slice bounds out of range)
	storage_test.go:356: 1348 error: internal error 052
FAIL
exit status 1
FAIL	github.com/cznic/ql	3.516s
jnml@4670:~/src/github.com/cznic/ql$
```

The fail starts [here](https://github.com/cznic/ql/blob/5078e40c8bb441d4ca66fd9a0486d965fd9b374a/stmt.go#L754) because `s.from.sources` is now allowed to be nil. Try to fix this particular place (difficulty: easy). I'll give you access rights to the repo in a moment. Please push your changes to the `issue155` branch. Please expect about/at most one round of feedback from me per day (~ a handful rounds per week) due to me beeing focused, unfortunately, on a different, long term task right now. Feel free to push more changes before I can respond if you think you're on the right track. Watch `go test` results, specifically for those in `testdata.ql` before number 1347, they must all continue to work after *any* changes of yours and *before* pushing them to the repo, thank you.

**Comment by gernest** [comment]
@cznic thanks!

For now, I will be working on the issue155 branch on my fork. I will push changes there and see if I can fix those tests. I will submit a PR when I succeed. So you can just focus on what you have been occupied with without worrying about this.

I don't feel confident enough to push changes directly to the repo 😄 . That can wait till I get more familiar with ql, for now PR based workflow looks more convenient!

**Comment by cznic** [comment]
No problem, works for me :smile:

**Comment by gernest** [comment]
@cznic thanks for the initial PR!

Please ping me when you add test case for finally addressing this! I will  fix them with a new PR!

I can't wait to have a full fledged object relational mapper that works with ql! 😄

**Comment by cznic** [comment]
@gernest 

I've added a couple of tests, two of them are failing (one existing, one new). The failing existing test no. 1348 is my fault and it must confused you when you wrote the implementation. My apologies.

Another thing which [does not seem right](https://github.com/cznic/ql/commit/3e161ea74936ab1b3b982166c14d21ac3c2bd290#diff-5147f21900633f77f14b931a29e2863cR8422): Why are the plans for no. 1350-1352 iterating no rows?

However, I guess it's just a minor problem to fix.

**Comment by gernest** [comment]
@cznic 

I think that iterate no row is a result of embedding `*nullPlan` I wanted to ask you for suggesting a good message but I forgot. see https://github.com/cznic/ql/blob/issue155/plan.go#L2826  which is used here https://github.com/cznic/ql/blob/issue155/ql.go#L549

If you suggest the explain message then I can submit a separate PR to fix it.

**Comment by gernest** [comment]
can you explain why test case 1348  is failing?

**Comment by gernest** [comment]
judging from the query, only one row macthes so it should have been

```sql
BEGIN TRANSACTION;
	CREATE TABLE t (i int);
	INSERT INTO t VALUES (1);
	INSERT INTO t VALUES (2);
	INSERT INTO t VALUES (3);
COMMIT;
SELECT * FROM t WHERE EXISTS (SELECT * FROM t WHERE i == 2) ORDER BY i;
|"i"
[2]
```

**Comment by cznic** [comment]
> can you explain why test case 1348 is failing?

Unfortunately not as I haven't yet a chance to look into it. But see [test no. 1353](https://github.com/cznic/ql/commit/3e161ea74936ab1b3b982166c14d21ac3c2bd290#diff-6733c042b94035cde51e784bf5ae0f29R15735) for illustration.

> judging from the query, only one row macthes so it should have been

Then the query would be equal to

```sql
BEGIN TRANSACTION;
	CREATE TABLE t (i int);
	INSERT INTO t VALUES (1);
	INSERT INTO t VALUES (2);
	INSERT INTO t VALUES (3);
COMMIT;
SELECT * FROM t WHERE i == 2 ORDER BY i;
```

But that's not what the new construct is supposed to do. The `WHERE` clause in 

```sql
WHERE EXISTS (SELECT * FROM t WHERE i == 2)
```

evaluates in this case to true because

```sql
SELECT * FROM t WHERE i == 2
```

Returns a non empty record set. So the outer `WHERE` clause is equal to `WHERE true`, cf. again no. 1353.

**Comment by gernest** [comment]
Thanks, now i understand

**Comment by gernest** [comment]
Uh! It looks like I will need to reimplement everything regarding `where exists`. The pieces don't match at all.

**Comment by cznic** [comment]
It's my fault. Once again, I am sorry.

But I don't think it needs too many changes. However, I am an hopelessly optimistic person ;-)

**Comment by gernest** [comment]
no problem! I will give it another spin..

**Comment by cznic** [comment]
@gernest Thanks for all your hard work! Branch `issue155` is now ready to be merged into branch `master`. You have all the rights to do that by your self. Feel free to squash or not to squash according to your preferences.

**Comment by gernest** [comment]
@cznic  thanks! I prefer to keep history, just in case one day we invent time traveling  machine! 😄

**Comment by gernest** [comment]
I'm closing this issue now.
