### ISSUE TITLE
exists field is not properly set on whereRset

### ISSUE THREAD

**Issue by gernest** [cznic/ql#157]
This is based on branch https://github.com/cznic/ql/tree/issue155

I did a siimple 

```go
func (r *whereRset) plan(ctx *execCtx) (plan, error) {
	if r.exists {
		pretty.Println(r.expr)
	}
```
to investigate the  value of the expression when the query is  `SELECT * FROM t WHERE EXISTS (SELECT * FROM t WHERE i == 2);`

I was expecting to see something on stdout, but nothing showed indicating the field was not properly set to boolean true.

**Comment by cznic** [comment]
This is a new feature required by #155 . The only thing already implemented is that the parser understands the construct and the `exists` field is filled by the proper values capture by the parser. The next step is to interpret those values. IIRC, there are only two, the presence of the `not` modifier and the parenthesized select statement. So implementing this new construct will execute the parenthesized select and on the first returned row, if any, evaluate to `true` or `false` accordingly.

Note: `r.expr` is nil when the `[not] exists` clause is used. That clause does not use an expression but the select statement in [`the sel field`](https://github.com/cznic/ql/blob/5078e40c8bb441d4ca66fd9a0486d965fd9b374a/ql.go#L335).

**Comment by cznic** [comment]
So the check in `whereRset` would be like

```
if r.sel != nil {
        ...
        return
}
```

otherwise it will fall back to the old implementation using the `expr` field.

**Comment by cznic** [comment]
See also [`parser.y`](https://github.com/cznic/ql/blob/5078e40c8bb441d4ca66fd9a0486d965fd9b374a/parser.y#L1320).

**Comment by gernest** [comment]
@cznic If the value is correctly populated by the parser in my check the if condition body should be executed.

I'm pretty sure the body was not executed as I couldn't care less for the value of `expr.`

**Comment by gernest** [comment]
Changing it to the snippet you provided

```
if r.sel != nil {
        ...
        return
}`
```

Also indicate the `r.sel` to always be nil which for our situation it should be something for the two test cases.

**Comment by cznic** [comment]
> If the value is correctly populated by the parser in my check the if condition body should be executed.

In the 

```go
if r.exists {
		pretty.Println(r.expr)
}
```

`r.expr` get printed, but it's nil for a where clause using `exists`.

> Changing it to the snippet you provided ... Also indicate the r.sel to always be nil which for our situation it should be something for the two test cases.

I'll try to reproduce. Give me 10 minutes ;-)

**Comment by cznic** [comment]
Please try https://github.com/cznic/ql/commit/f530724f84a5ac23ce1c2b8061efe696a17e5e24

The test:

```go
func TestTmp(t *testing.T) {
	list := MustCompile("select a from b where exists (select c from d)")
	sel := list.l[0].(*selectStmt)
	dbg("", sel.where.sel)
}
```

Run:

```bash
$ go test -v -run Tmp
=== RUN   TestTmp
dbg all_test.go:3441: SELECT c FROM d; 
--- PASS: TestTmp (0.00s)
PASS
ok  	github.com/cznic/ql	0.005s
```

**Comment by gernest** [comment]
@cznic thanks. 

I have verified from the test case that indeed the values were properly populated. I'm closing the issue now.
