### ISSUE TITLE
Adding  support of INNER JOIN

### ISSUE THREAD

**Issue by gernest** [cznic/ql#160]
This is a  feature request.

I'm finalizing supporting ql in the ORM I'm hacking on. While fixing Many to many relation I am supposed to use INNER JOIN. I Have found OUTER JOIN is already supported so Maybe INNER JOIN will be possible as well.

Thanks

**Comment by gernest** [comment]
It is like I have the following schema

```
BEGIN TRANSACTION;
    CREATE TABLE blogs (id int64,locale string,subject string,body string ) ;
    CREATE TABLE tags (id int64,locale string,value string ) ;
    CREATE TABLE blogs_tags (tag_id int64,tag_locale string,blog_id int64,blog_locale string ) ;
COMMIT;

```

And I would like to run the following query

```sql
SELECT count(*) 
FROM   tags 
       INNER JOIN blog_tags 
               ON blog_tags.tag_id = tags.id 
                  AND blog_tags.tag_locale = tags.locale 
WHERE  ( ( blog_tags.blog_id, blog_tags.blog_locale ) IN (( $1, $2 )) ) 
```

**Comment by cznic** [comment]
@gernest IIRC correctly, `INNER JOIN` is the same as `CROSS JOIN`. IOW, your query should be equal to something like (not tested)

```sql
SELECT count(*) 
FROM   tags , blog_tags
WHERE blog_tags.tag_id = tags.id
        AND blog_tags.tag_locale = tags.locale
        AND (( blog_tags.blog_id, blog_tags.blog_locale ) IN ( $1, $2 ));
```

Can you please test it?

**Comment by gernest** [comment]
@cznic I copied the query verbatin

I get this error

`
unexpected ',', expected logical or operator or one of [')', OR, ||]
`

**Comment by gernest** [comment]
For some reason I noticed the issue is with this part of the query. QL seeems to fail compiling it/parse it I suppose.

```sql
        AND (( blog_tags.blog_id, blog_tags.blog_locale ) IN ( $1, $2 ));
```

After I  changed it not use IN it worked

```sql
        AND blog_tags.blog_id - $1
        AND  blog_tags.blog_locale = $2 
```

Thanks,
