### ISSUE TITLE
ql does not support cyrillic in table or columns name?

### ISSUE THREAD

**Issue by DeadNumbers** [cznic/ql#174]
```Go
package main

import (
	"database/sql"
	"log"

	"github.com/cznic/ql"
)

func main() {
	ql.RegisterDriver()
	db, _ := sql.Open("ql", "/tmp/ql.db")
	tx, _ := db.Begin()

	_, err := tx.Exec("create table пользователи(имя string, адрес string)")
	if err != nil {
		log.Fatal(err)
	}
	_, err = tx.Exec("insert into пользователи(имя, адрес) values($1,$2)", "иван", "москва")
	if err != nil {
		log.Fatal(err)
	}
	err = tx.Commit()
	if err != nil {
		log.Fatal(err)
	}
	println("done")
}
```
>./test_cyrillic
>>2017/05/10 17:51:41 1:14 unexpected 208, expected table name or one of [IF, identifier]

**Comment by cznic** [comment]
The [documentation](http://godoc.org/github.com/cznic/ql) says:

[Identifiers](https://godoc.org/github.com/cznic/ql#hdr-Identifiers): `identifier = letter { letter | decimal_digit } .`

[Letters and digits](https://godoc.org/github.com/cznic/ql#hdr-Letters_and_digits): `letter        = ascii_letter | "_" .`

[Characters](https://godoc.org/github.com/cznic/ql#hdr-Characters): `ascii_letter   = "a" … "z" | "A" … "Z" .`.

So no, identifiers can have only ASCII letters, digits and the '_' character.

**Comment by DeadNumbers** [comment]
So sad. Thanks for answer.

**Comment by DeadNumbers** [comment]
@cznic How I can add cyrillic? I create this https://github.com/DeadNumbers/ql/commit/861e690485258e1884be25be0f562368cab9429f but does not work.

**Comment by cznic** [comment]
The ql.ebnf is generated from the documentation.

To add support for Unicode letters in identifiers the necessary changes have to be done in the [tokenizer](https://github.com/cznic/ql/blob/eb22df22d0ac223dcd91f16d6de0fc4cfdf768a5/scanner.l#L206). Please open a separate issue/feature request for this, maybe I can find some time this weekend to implement it.
