### ISSUE TITLE
Request: adding unicode supporting

### ISSUE THREAD

**Issue by DeadNumbers** [cznic/ql#176]

**Comment by cznic** [comment]
cf. #174

**Comment by cznic** [comment]
@DeadNumbers Please test branch issue176 and let me know if it works for you, thanks.

**Comment by DeadNumbers** [comment]
@cznic work! Thanks you!

**Comment by cznic** [comment]
Fixed in https://github.com/cznic/ql/commit/ba9eea98e3d20b3485b5b3d4a77775ee8bdd5387.
