### ISSUE TITLE
WHERE and aliased columns

### ISSUE THREAD

**Issue by xiam** [cznic/ql#182]
Hello,

I have a query that uses aliases for columns that would normally work on other SQL databases:

`SELECT id() AS id, name FROM artist WHERE (id < 100) ORDER BY id DESC LIMIT 15`

But it doesn't work in ql:

`2017/06/28 11:34:57 unknown field id: BEGIN TRANSACTION;`

The problem seems to be on the WHERE statement, ORDER BY works just fine:

`SELECT id() AS id, name FROM artist ORDER BY id DESC LIMIT 15`

Is it possible to use column aliases in WHERE statements without using this subquery syntax?

`SELECT * FROM (SELECT id() AS id, name FROM artist) WHERE (id < 100) ORDER BY id DESC LIMIT 15`

**Comment by cznic** [comment]
>  `SELECT id() AS id, name FROM artist WHERE (id < 100) ORDER BY id DESC LIMIT 15`

I think this cannot not work because of the SELECT statement [evaluation order](https://godoc.org/github.com/cznic/ql#hdr-Select_statement_evaluation_order), bullets 3 vs 5.


Can you please try

```sql
SELECT name FROM artist WHERE id() < 100 ORDER BY id() DESC LIMIT 15
```

I'm not sure if it should work, but I guess so.

**Comment by cznic** [comment]
@xiam Gentle ping: Please provide feedback so we can determine if the issue can be closed or if there's something to do here, thank you.

**Comment by xiam** [comment]
Hello @cznic, thanks for your answer, I think it makes sense. Let's close this issue.
