### ISSUE TITLE
issue: driver.NamedValue is undefined

### ISSUE THREAD

**Issue by Spefer** [cznic/ql#185]
go get github.com/cznic/ql/ql
# github.com/cznic/ql
go/src/github.com/cznic/ql/driver1.8.go:16: undefined: driver.NamedValue
go/src/github.com/cznic/ql/driver1.8.go:20: undefined: driver.NamedValue
go/src/github.com/cznic/ql/driver1.8.go:31: undefined: driver.NamedValue
go/src/github.com/cznic/ql/driver1.8.go:58: undefined: driver.NamedValue
go/src/github.com/cznic/ql/driver1.8.go:66: undefined: driver.NamedValue

**Comment by cznic** [comment]
@gernest Please take a look, thanks.

**Comment by twitchyliquid64** [comment]
What go version are you running? NamedValue was introduced recently.

Did you install Go with Brew? There be dragons.

**Comment by Spefer** [comment]
@twitchyliquid64 no, just unpack the golang package into one folder and  have this issue when try to perform go get

**Comment by Spefer** [comment]
go 1.8

**Comment by gernest** [comment]
@Spefer can you please give more context. If you are using `go1.8` then the  `driver.NamedValue`  was added there.

There is nothing I can do at the moment, until i can reproduce it please advice.

**Comment by Spefer** [comment]
closed it for I have 2 go version installed and it would use old version rather then 1.8 when I perform go get command, thanks you all
