### ISSUE TITLE
Cannot use basic table From Mysql/ Postrges/ Sqlite3

### ISSUE THREAD

**Issue by hibooboo2** [cznic/ql#186]
I have this code: https://gist.github.com/hibooboo2/7151c5f0edcae8539cbd8ea54d5e2313

Which uses these tables: 

```go
var tables = [...]string{`CREATE TABLE IF NOT EXISTS things (
	some_name varchar(256) NOT NULL,
	type int NOT NULL,
	idle_timeout int NOT NULL,
	config text NOT NULL,
	PRIMARY KEY (some_name, type)
);`,

	`CREATE TABLE IF NOT EXISTS otherthings (
	name varchar(256) NOT NULL PRIMARY KEY,
	config text NOT NULL
);`,
}
```

And I cannot execute them in to the ql database. I have something I am working on where we support alot of sql databases and wanted to add really badly but cannot even add our tables. When I tried it seemed like you do not support varchar so I tried removing that but to no avail still blew up.

**Comment by gernest** [comment]
@hibooboo2 

ql is a bit different. I have tried to get ql equivalent of the DDL you procided 

```sql
CREATE TABLE IF NOT EXISTS things (
	some_name string  NOT NULL,
	type int NOT NULL,
	idle_timeout int NOT NULL,
	config string NOT NULL,
);

CREATE TABLE IF NOT EXISTS otherthings (
	name string NOT NULL,
	config string NOT NULL
);
```

There is no `PRIMARY KEY` in ql.

If what you are working on is public( on github ), I can help you add support for ql.

**Comment by hibooboo2** [comment]
I could special case it but was hoping to be able to just use all of our
sql as is with sqlx. 😉

**Comment by gernest** [comment]
I see, I haven't used sqlx. But If there is anything I can help you with ql please let me know.

 I have been looking for an excuse to hack something with ql, so can you expand a little bit about your problem, and how it is realted to sqlx?

One note though, in [ngorm](https://github.com/ngorm/ngorm) which I'm maintaining, You can use the same logic for `ql` and `postgresql` and `mysql` and `sqlite`. That is an ORM though. Is what you are working on an ORMish thing? Just curious.

**Comment by hibooboo2** [comment]
We do not use an orm. The nice thing about sqlx is it is a very think wrapper around database/sql to allow you to do what that does with some sugar. And it would be super cool of ql was a drop in embeddable  full on SQL implementation like sqlite etc.. But I guess its not. Which is fine. Just got really excited when I found this project and then sad... Ahh well maybe someday.

**Comment by gernest** [comment]
@hibooboo2 you can close this issue , if your questions have been answered. If there is anything else regarding this issue please ask.

**Comment by hibooboo2** [comment]
It's the details for ql too be a drop in replacement for an sql db such as
mysql or PostgreSQL or no?

**Comment by gernest** [comment]
@hibooboo2 nope, ql is not meant to be a drop in replacement for msql or postgresql

**Comment by hibooboo2** [comment]
K closing this. Thanks
