### ISSUE TITLE
Support adding constrained columns on tables with existing data

### ISSUE THREAD

**Issue by bspaans** [cznic/ql#193]
When I try to alter an existing table:

`ALTER TABLE existing_table ADD something string NOT NULL DEFAULT "text";`

I get this error message:

`ALTER TABLE existing_table ADD something: cannot add constrained column to table with existing data in line 0`

I don't know much about the internals of ql, but would it be possible to support this?

**Comment by cznic** [comment]
It is possible to certain extent support that. The problematic parts are:

- It'll have to check every existing row of the table and thus take a long time.
- If the constraint fails at any row, it'll have to undo any mutation made to the table so far and thus take even more time.

For the above reasons the feature is not implemented. It's still possible to do the equivalent operation by doing:

- create an empty temporary table with the desired schema including the constraint
- try to import the existing data into into the temporary table
- if ok, delete all rows from the existing table, update the schema with the constraint and import the temporary table data into it.

The above "external" steps are not the fastest way how to workaround the issue, but probably a safe approach.

You're welcome if you would like to implement and contribute the feature internally in ql. Basically, it's just reproducing the above steps. Initially, just calling a few ql (ie text) statements reproducing the above steps would be enough and rather easy to implement, I guess.

WDYT?

**Comment by bspaans** [comment]
Thanks for the quick reply! 

I think it makes sense to apply the changes to a temporary table first. As far as I can tell `ALTER` statements usually have an implicit COMMIT so transactions shouldn't be an issue either. I might have a go at implementing this at some point, but will try the SQL workaround you mentioned first. Thanks!

**Comment by cznic** [comment]
Assuming you're using the workaround and closing. Feel free to reopen/re-report the issue if needed.
