### ISSUE TITLE
vgo get issue - expected?

### ISSUE THREAD

**Issue by shogsbro** [cznic/ql#199]
$ vgo get github.com/cznic/ql
vgo: finding github.com/cznic/ql v1.1.0
vgo: downloading github.com/cznic/ql v1.1.0
vgo: resolving import "github.com/cznic/b"
vgo: finding github.com/cznic/b (latest)
vgo: adding github.com/cznic/b v0.0.0-20180115125044-35e9bbe41f07
vgo: resolving import "github.com/cznic/lldb"
vgo: finding github.com/cznic/lldb (latest)
vgo: adding github.com/cznic/lldb v1.1.0
vgo: resolving import "github.com/cznic/mathutil"
vgo: finding github.com/cznic/mathutil (latest)
vgo: adding github.com/cznic/mathutil v0.0.0-20180504122225-ca4c9f2c1369
vgo: resolving import "github.com/cznic/strutil"
vgo: finding github.com/cznic/strutil (latest)
vgo: adding github.com/cznic/strutil v0.0.0-20171016134553-529a34b1c186
vgo: finding github.com/cznic/strutil v0.0.0-20171016134553-529a34b1c186
vgo: finding github.com/cznic/mathutil v0.0.0-20180504122225-ca4c9f2c1369
vgo: finding github.com/cznic/lldb v1.1.0
vgo: finding github.com/cznic/b v0.0.0-20180115125044-35e9bbe41f07
vgo: downloading github.com/cznic/b v0.0.0-20180115125044-35e9bbe41f07
vgo: downloading github.com/cznic/lldb v1.1.0
vgo: downloading github.com/cznic/mathutil v0.0.0-20180504122225-ca4c9f2c1369
vgo: downloading github.com/cznic/strutil v0.0.0-20171016134553-529a34b1c186
vgo: resolving import "github.com/cznic/fileutil"
vgo: finding github.com/cznic/fileutil (latest)
vgo: adding github.com/cznic/fileutil v0.0.0-20180108211300-6a051e75936f
vgo: resolving import "github.com/cznic/internal/buffer"
vgo: finding github.com/cznic/internal (latest)
vgo: adding github.com/cznic/internal v0.0.0-20170905175358-4747030f7cf2
vgo: resolving import "github.com/cznic/sortutil"
vgo: finding github.com/cznic/sortutil (latest)
vgo: adding github.com/cznic/sortutil v0.0.0-20150617083342-4c7342852e65
vgo: resolving import "github.com/cznic/zappy"
vgo: finding github.com/cznic/zappy (latest)
vgo: adding github.com/cznic/zappy v0.0.0-20160723133515-2533cb5b45cc
vgo: finding github.com/cznic/zappy v0.0.0-20160723133515-2533cb5b45cc
vgo: finding github.com/cznic/sortutil v0.0.0-20150617083342-4c7342852e65
vgo: finding github.com/cznic/internal v0.0.0-20170905175358-4747030f7cf2
vgo: finding github.com/cznic/fileutil v0.0.0-20180108211300-6a051e75936f
vgo: downloading github.com/cznic/fileutil v0.0.0-20180108211300-6a051e75936f
vgo: downloading github.com/cznic/internal v0.0.0-20170905175358-4747030f7cf2
vgo: downloading github.com/cznic/sortutil v0.0.0-20150617083342-4c7342852e65
vgo: downloading github.com/cznic/zappy v0.0.0-20160723133515-2533cb5b45cc
vgo: resolving import "github.com/edsrzf/mmap-go"
vgo: finding github.com/edsrzf/mmap-go (latest)
vgo: adding github.com/edsrzf/mmap-go v0.0.0-20170320065105-0bce6a688712
vgo: finding github.com/edsrzf/mmap-go v0.0.0-20170320065105-0bce6a688712
vgo: downloading github.com/edsrzf/mmap-go v0.0.0-20170320065105-0bce6a688712
../../../../go/src/v/github.com/cznic/lldb@v1.1.0/btree.go:16:2: use of internal package not allowed
../../../../go/src/v/github.com/cznic/lldb@v1.1.0/memfiler.go:13:2: use of internal package not allowed
../../../../go/src/v/github.com/cznic/internal@v0.0.0-20170905175358-4747030f7cf2/buffer/buffer.go:36:2: use of internal package not allowed

**Comment by cznic** [comment]
@shogsbro I've tried to provide more info at https://github.com/golang/go/issues/25164#issuecomment-392083411.

**Comment by sbinet** [comment]
can be closed as well. (see cznic/internal#5.)

**Comment by cznic** [comment]
Thanks @sbinet , closing.
