### ISSUE TITLE
release: tag a new release with Go modules support ?

### ISSUE THREAD

**Issue by sbinet** [cznic/ql#205]
now that https://github.com/cznic/ql/pull/204 is in, `cznic/ql` has (initial) support for Go modules.

do you think we could tag it (`v1.2.0`? `v1.1.1`?) so `go mod tidy` would pick it up in downstream clients?

**Comment by cznic** [comment]
So far I've never used git tags nor Go modules and I have insufficient knowledge about both of that to answer your question.

I think you know what's the best to do in this case and you're a trusted developer by many, me included.

Would you mind to take care of this on your own? I hope to learn from the steps you will take ;-)

Partially related: You've contributed to this project but I forgot to ask you to also add yourself to the AUTHORS and/or CONTRIBUTORS files. Please do so, thank you.

**Comment by sbinet** [comment]
thanks for the vote of confidence :)

I'll add myself to the `CONTRIBUTORS` file and then run `git tag v1.2.0`.

I think that's all there is to it. (oops, I'll also add a little blurb to `doc.go`.)
I am learning also the best practices for Go with modules...
