### ISSUE TITLE
subquery no result

### ISSUE THREAD

**Issue by avelner** [cznic/ql#208]
```
$ cat test2.txt 

echo MySQL

mysql -uroot -p test << EOF
DROP TABLE IF EXISTS test;
CREATE TABLE test (a int not null, b int not null);
INSERT INTO test (a, b) VALUES (0, 4);
INSERT INTO test (a, b) VALUES (1, 5);
SELECT DISTINCT a FROM test WHERE a NOT IN (SELECT a FROM test WHERE b = 9)
EOF

echo 
echo QL

rm -f test.db
ql -fld -db test.db << EOF
DROP TABLE IF EXISTS test;
CREATE TABLE test (a int not null, b int not null);
INSERT INTO test (a, b) VALUES (0, 4);
INSERT INTO test (a, b) VALUES (1, 5);
SELECT DISTINCT a FROM test WHERE a NOT IN (SELECT a FROM test WHERE b = 9)
EOF

$ bash test2.txt 
MySQL
Enter password: 
a
0
1

QL
"a"
```

Problem no result from QL

**Comment by avelner** [comment]
Is there a way that I can help  (haven't looked at the code base yet)

Problem seems to be a subquery which does not return results:

SELECT DISTINCT a FROM test WHERE a NOT IN (SELECT a FROM test where 1 = 0);
gives no results

SELECT DISTINCT a FROM test WHERE a NOT IN (SELECT 1 AS a);
gives error: IN (SELECT 1 AS a;): invalid field type: ql.idealInt

queries below give correct results
SELECT DISTINCT a FROM test WHERE a NOT IN (NULL);
SELECT DISTINCT a FROM test WHERE a NOT IN (5);
SELECT DISTINCT a FROM test WHERE a NOT IN (SELECT a FROM test WHERE b = 5);"

**Comment by avelner** [comment]
in expr.go is says (around line 3264)

```
if ev.sample == nil {
                return nil, nil
}       
```

which should be (i think)

```
if ev.sample == nil {
                return !n.not, nil
}       
```

can you check this

**Comment by cznic** [comment]
@avelner Please test branch `issue208` if the fix works for you. Thanks.

**Comment by avelner** [comment]
will test tonight, have to travel now

**Comment by avelner** [comment]
Tested, works, thanks for the quick response.
