### ISSUE TITLE
question about subqueries

### ISSUE THREAD

**Issue by cryptix** [cznic/ql#72]
I want to drop rows in `tableA` that have no reference in `tableB` (simple `1:n`) but I can't figure out the QL syntax for it.

Something like this would work in other sql's.
```sql
select id() from tableA where id() not in (select idA from tableB);
```

I also tried doing the sub-query in the `from` field but I only get `syntax error`'s...
If it doesn't work (currently) I could work around it by doing it in two separate queries, I guess.

edit: guess I can't do the latter.. ` sql: converting Exec argument #0's type: unsupported type []int64, a slice`

edit2: I could construct the query string with `fmt` but that definitely feels to much like php... I hope there is another way and I just missed the important sentence in the docs.

**Comment by cznic** [comment]
> Change list
>
>2015-02-16: IN predicate now accepts a SELECT statement. See the updated "Predicates" section.

----

> Another form of the IN predicate creates the expression list from a result of a SelectStmt.
>
> `DELETE FROM t WHERE id() IN (SELECT id_t FROM u WHERE inactive_days > 365)`
>
>
> The SelectStmt must select only one column. The produced expression list is resource limited by the 
> memory available to the process. NULL values produced by the SelectStmt are ignored, but if all 
> records of the SelectStmt are NULL the predicate yields NULL. The select statement is evaluated 
> only once. If the type of expr is not the same as the type of the field returned by the SelectStmt then 
> the set operation yields false. The type of the column returned by the SelectStmt must be one of the 
> simple (non blob-like) types:
>
> `bool`
> `byte         // alias uint8`
> `complex1`
> `complex64`
> `float        // alias float64`
> `float32`
> `float64`
> `int          // alias int64`
> `int16`
> `int32`
> `int64`
> `int8`
> `rune`
> `string`
> `uint         // alias uint64`
> `uint16`
> `uint32`
> `uint64`
> `uint8`

----

```
Predicate = (
	[ "NOT" ] (
			"IN" "(" ExpressionList ")"
			| "IN" "(" SelectStmt ")"
			| "BETWEEN" PrimaryFactor "AND" PrimaryFactor
		)
	| "IS" [ "NOT" ] "NULL"
).
```

Commit follows.

**Comment by cryptix** [comment]
Very nice! Highly appreciated!

**Comment by cznic** [comment]
Sorry it took so long. Glad if it's useful ;-)

**Comment by cznic** [comment]
The implementation violated an important invariant - execution domain data must be held outside of the implementing instance (`type pIn` in this case). Reproduction case added as well as the fix (commit follows).

**Comment by cznic** [comment]
@cryptix 
Please udpdate your local copy.

**Comment by cryptix** [comment]
@cznic thanks for the heads up!!! The new stuff only was in our dev branch until know. :relieved:
