### ISSUE TITLE
cryptic syntax error when using && instead of AND in WHERE clause

### ISSUE THREAD

**Issue by nictuku** [cznic/ql#81]
I'm getting a cryptic syntax error when I use AND in my WHERE clause.

        mail := "yves.junqueira@gmail.com"
        rows, err := db.Query(`SELECT content, t FROM profiles WHERE name == "heap" AND user == $1 ORDER BY t DESC LIMIT 1;`, mail)
        if err != nil {
                log.Fatalln("QUERY error:", err)
        }
        // Result: 2015/01/17 20:50:07 QUERY error: 1:54 syntax error

This is because I'm using AND instead of &&. I'm used to AND in SQL and I had the impression that it's fairly standard.

Two minor problems:
- the error is cryptic. Could it somehow be a bit more clear? Maybe it could say which clause it encountered that it didn't understand?
- would it be possible to accept `AND` in such cases? AFAIK it's legal in most SQL systems I've used.

Thank you for the great work on ql.

**Comment by cznic** [comment]
> the error is cryptic

True. See #80.

**Comment by nictuku** [comment]
Fantastic, thank you!
