### ISSUE TITLE
QL not really "pure Go" - go get pulls in cznic/zappy that needs CGO environment

### ISSUE THREAD

**Issue by srinathh** [cznic/ql#86]
I was trying to use QL on a Windows machine that does not have a C dev environment (and it is difficult to set one up because of work restrictions) mainly to get a simple "Pure Go" SQL embedded database. However, go get failed on a dependency that required a C environment   

Is there a way to build QL as a "truly pure Go" library without any C dependencies?

**Comment by cznic** [comment]
The C dependency is a speed improvement of [zappy](http://godoc.org/github.com/cznic/zappy) and it can be [disabled](http://godoc.org/github.com/cznic/zappy#hdr-Build_tags):

> If a constraint 'purego' appears in the build constraints [5] then a pure Go version is built regardless of the $CGO_ENABLED value.

Please try (tested):

```bash
$ cd $GOPATH/src/github.com/cznic/ql
$ go clean -i ./...
$ go install -v -tags purego ./...
```

Alternatively, using go get (not tested):
```
$ go get -u -tags purego github.com/cznic/ql/...
```

**Comment by srinathh** [comment]
Thanks! I can confirm the `go get` command line also seems to work... may I suggest adding it as an option in the README since one of the attractive features of QL is lack of CGO dependencies

**Comment by extemporalgenome** [comment]
If it's just a speed improvement (functionally transparent), would it not be worth having a pure Go build be the default?

**Comment by cznic** [comment]
If I would have to decide it today, I would do it the way you suggest. But I don't want to change what's not broken - to avoid breaking something else I cannot foresee.

**Comment by extemporalgenome** [comment]
Of course ;)
