### ISSUE TITLE
QL Parameter in WHERE

### ISSUE THREAD

**Issue by rHermes** [cznic/ql#97]
I'm trying to use this: 

```go
var authorLoad = ql.MustCompile(`
	SELECT id(), Username, Email, Joined FROM Author WHERE $1 == $2;
`)
```
And it compiles, and I can use it in db.Execute, but it doesn't return a result. When I change $1 to Username and $2 to $1 and only pass one parameter to db.execute it works.

Am I doing something wrong or is this a bug?

**Comment by cznic** [comment]
What are the two parameters you're passing? If they are `"Username"` and `"foo"` (for example) then execution of that query is equal to have a `WHERE false` clause, because the two strings are not equal. IOW, the column name to use in the comparison cannot be parametrized.

**Comment by rHermes** [comment]
Ok, thank you :) Is there any plans to add support for such a feature?

**Comment by cznic** [comment]
No plans ATM. However: Are you aware of a SQL database which supports this feature? If so, I would love to take a look on the implementation details/semantics and think about it.

**Comment by rHermes** [comment]
I am very new to SQL in general!

QL is the first I've ever read the entire specification too, so I couldn't point you in any direction :)

For now I have just switched the code posted above for several hardcoded versions, and put a switch statement in the function that took the field. I just thought the idea was neat, it's no big thing.

I do want to give you a huge thank for making QL, I hope that I can one day contribute to the Go community in such a way!

**Comment by cznic** [comment]
> QL is the first I've ever read the entire specification too...

You might be the first human to do so (entirely) except myself ;-)

> For now I have just switched the code posted above for several hardcoded versions, and put a switch statement in the function that took the field. I just thought the idea was neat, it's no big thing.

I think it's possible to invent built-ins like `table(arg string)` or `column(arg string)` which will evaluate `arg` as a table or column respectively. I guess that this is not generally supported because it makes statement optimizing harder or perhaps even impossible in some cases. Another reason could be a security risk of allowing parameters to represent tables or colums.

> I hope that I can one day contribute to the Go community in such a way!

I'm sure you will!

**Comment by steveno** [comment]
This is basically dynamic sql. 

Check this link in oracle docs for a quick overview. 


http://docs.oracle.com/cd/B28359_01/appdev.111/b28427/pc_13dyn.htm#i2160

**Comment by steveno** [comment]
That link didn't really go in the document where I wanted. Sorry. Check the "Methods for using dynamic sql" section Method 4.

**Comment by cznic** [comment]
@steveno Thank you very much for the reference! My first impression is that the Oracle's solution is way more complex than I'd probably ever like to try to implement.

IMO, if there's some convincing argument for the technique mentioned in https://github.com/cznic/ql/issues/97#issuecomment-99852167, then I might change my mind, but for now I think even that minimalistic approach has more disadvantiges than the value it may add.

In any case, please share your thought and opinions, it would be welcome. Thanks.

**Comment by rHermes** [comment]
I think QL should be simple, like it is now. The simpler and more straightforward the queries we are allowed to write are, the easier it will be for the optimizer to do it's job. 

Also thanks @stevno for the interesting read! Oracle sure has a lot of nice articles :D
