### ISSUE TITLE
Record id is not table-unique

### ISSUE THREAD

**Issue by rHermes** [cznic/ql#98]
It stands in the spec:
http://godoc.org/github.com/cznic/ql#hdr-Record_id
That the record id should be table-unique, but when creating records in different tables, it seems to me that the Record id is unique across the entire db.

Starting With two empty tables A and B, and creating an entry in first A then B, doing "Select id() FROM B" will yield 2, not 1.

Is this intentional or a bug?

**Comment by cznic** [comment]
> Is this intentional or a bug?

```bash
(10:07) jnml@r550:~/tmp$ rm -f ql.db
(10:07) jnml@r550:~/tmp$ ql 'create table a (i int)'
(10:07) jnml@r550:~/tmp$ ql 'create table b (i int)'
(10:08) jnml@r550:~/tmp$ ql 'insert into a values(42)'
(10:08) jnml@r550:~/tmp$ ql 'insert into b values(314)'
(10:08) jnml@r550:~/tmp$ ql 'select id() from a'
1
(10:08) jnml@r550:~/tmp$ ql 'select id() from b'
2
(10:08) jnml@r550:~/tmp$ 

```

The ids seen above are table-unique as specified. So it's not a bug.

Note: Except for being table-unique, no other guarantees about the _values_ of table ids are given in the specs.

**Comment by rHermes** [comment]
Aww, I should have seen that :)
