### ISSUE TITLE
Memory/something leak

### ISSUE THREAD

**Issue by sitano** [cznic/ql#99]
1) Inserting wide rows with a lot of columns (~100) takes very long time. 
Like inserting 100 rows 100 columns wide take 4000ms on my super machine.

2) Table recreation with DROP/TRUNCATE TABLE go QL crazy for huge leak of something. Time execution of inserts grows after every refill of inmemory db.

My test:

```
function Recreate {
- drop table if exists
- create table 100 columns wide
}

function Fill {
- fill 100 rows into table
}

1 .. 100 | {
- Recreate
- Fill
}
```

$ go tool pprof -alloc_objects

```
(pprof) top10
706132470 of 712949203 total (99.04%)
Dropped 64 nodes (cum <= 3564746)
Showing top 10 nodes out of 34 (cum >= 709388633)
      flat  flat%   sum%        cum   cum%
 312245257 43.80% 43.80%  312245257 43.80%  github.com/cznic/ql.(*mem).clone
 287752964 40.36% 84.16%  390531686 54.78%  github.com/cznic/ql.func·025
  99288551 13.93% 98.08%   99288551 13.93%  github.com/cznic/ql.(*ident).eval
   3481676  0.49% 98.57%    7389621  1.04%  github.com/cznic/ql.func·029
    786442  0.11% 98.68%  704617500 98.83%  github.com/cznic/ql.(*selectRset).do
    727471   0.1% 98.78%  705661737 98.98%  github.com/cznic/ql.constraintsAndDefaults
    655367 0.092% 98.88%  703186611 98.63%  github.com/cznic/ql.(*crossJoinRset).do
    644447  0.09% 98.97%  703831058 98.72%  github.com/cznic/ql.(*whereRset).do
    288147  0.04% 99.01%  712031605 99.87%  pluginsync/cache.(*NodeCacheDatabase).insertData
    262148 0.037% 99.04%  709388633 99.50%  github.com/cznic/ql.driverExec
```

**Comment by cznic** [comment]
Thanks for the report! Any repro code available would be useful to look at.

**Comment by sitano** [comment]
actually, i dont have in public, but the idea is as follows:

```
func createTables(db *sql.DB) error {
	var tx *sql.Tx
	var err error

	tx, err = db.Begin()

	if err == nil {
		_, err = tx.Exec(`
                DROP TABLE IF EXISTS Node;
		CREATE TABLE Node (Datacenter string, Name string, Address string, Health bool, ........ 100 other columns ..... );		
		`)
	}

	if err == nil {
		err = tx.Commit()
	}

	return err
}
```

**Comment by cznic** [comment]
Thanks! Hope to dive into it this weekend.

**Comment by sitano** [comment]
Awesome, thanks! 

I did not find any info in your profile about Company or Purpose of this project. Can you share some info on your motivation on this?

Thanks btw for this project on Go. I use QL for querying cluster of Consul servers for its data.

**Comment by cznic** [comment]
@sitano 

I tried to reproduce the problem but I'm doing something wrong or I'm doing something diffently than you're doing.

Please try
```bash
$ cd $GOPATH/github.com/cznic/ql
$ git fetch
$ git checkout issue99
$ go test -v -bench Issue99 -benchmem -run Issue99
```

It would be nice to let me know what you get on your PC.

> Like inserting 100 rows 100 columns wide take 4000ms on my super machine.

My machine (Intel 4670 @ 3.4 Ghz) outputs
```
=== RUN TestIssue99
--- PASS: TestIssue99 (2.32s)
	issue99_test.go:310: Total rows inserted 10000
PASS
BenchmarkIssue99	       1	2349440138 ns/op	4256.33 MB/s	418614184 B/op	10160353 allocs/op
--- BENCH: BenchmarkIssue99
	all_test.go:330: 
		=============================================================
		NOTE: All benchmarks report records/s as 1000000 bytes/s.
		=============================================================
	issue99_test.go:321: 1 op == (Re)create a 100+ column table, fill it with 100 records. Repeat 100 times.
		
ok  	github.com/cznic/ql	4.681s
```

The above means the same takes on average < 24 milliseconds on my machine. Please review the test/bench [code](https://github.com/cznic/ql/blob/issue99/issue99_test.go) for this issue and look for my bugs and or differences wrt to your code - and please let my know about your findings. Thanks in advance!

PS:

> Can you share some info on your motivation on this?

As many other projects - scratching my own itch, i.e. I needed a pure Go SQL-like DB and I was not aware of any existing one.

**Comment by cznic** [comment]
@sitano FYI: A modified test and benchmark was added. It uses a prepared statement and here is how the two versions compare

```
$ git branch
  dev
* issue99
  master
$ go test -v -run Issue99 -bench Issue99 -benchmem
=== RUN TestIssue99
--- PASS: TestIssue99 (2.29s)
	issue99_test.go:355: Total rows inserted 10000
=== RUN TestIssue99B
--- PASS: TestIssue99B (0.57s)
	issue99_test.go:390: Total rows inserted 10000
PASS
BenchmarkIssue99	       1	2296109411 ns/op	4355.19 MB/s	418608088 B/op	10160283 allocs/op
--- BENCH: BenchmarkIssue99
	all_test.go:330: 
		=============================================================
		NOTE: All benchmarks report records/s as 1000000 bytes/s.
		=============================================================
	issue99_test.go:366: 1 op == (Re)create a 100+ column table, fill it with 100 records. Repeat 100 times.
		
BenchmarkIssue99B	       2	 571390116 ns/op	17501.18 MB/s	188293028 B/op	 2636318 allocs/op
--- BENCH: BenchmarkIssue99B
	issue99_test.go:401: 1 op == (Re)create a 100+ column table, fill it with 100 records. Repeat 100 times.
		
ok  	github.com/cznic/ql	6.873s
$ 
```

IOW, parsing the long insert statement in its textual form dominates both the time and memory consumption. Using the prepared statement seems to lower the average time to insert a 100+ column row to about 57 microseconds.

**Comment by sitano** [comment]
yes, your test looks good:

```
=== RUN TestIssue99
--- PASS: TestIssue99 (2.51s)
	issue99_test.go:355: Total rows inserted 10000
=== RUN TestIssue99B
--- PASS: TestIssue99B (0.59s)
	issue99_test.go:390: Total rows inserted 10000
PASS
BenchmarkIssue99	       1	2445763505 ns/op	4088.70 MB/s	418608632 B/op	10160279 allocs/op
--- BENCH: BenchmarkIssue99
	all_test.go:330: 
		=============================================================
		NOTE: All benchmarks report records/s as 1000000 bytes/s.
		=============================================================
	issue99_test.go:366: 1 op == (Re)create a 100+ column table, fill it with 100 records. Repeat 100 times.
		
BenchmarkIssue99B	       2	 597361322 ns/op	16740.29 MB/s	188294940 B/op	 2636356 allocs/op
--- BENCH: BenchmarkIssue99B
	issue99_test.go:401: 1 op == (Re)create a 100+ column table, fill it with 100 records. Repeat 100 times.
		
ok  	github.com/cznic/ql	7.349s
```

i will do some research and make a report a bit later this week. thnx.

**Comment by sitano** [comment]
I have found it! ;)

The issue is the CONSTRAINTs which are over FIELDS in the table definition (string DEFAULT "").

https://gist.github.com/sitano/a9260aac7bd40bc5310b

**Comment by cznic** [comment]
Thank you very much @sitano for your contribution. Please test and please don't hesitate to report any (other) problem(s).

**Comment by sitano** [comment]
Thank you @cznic too for your fast and outstanding support and
conversation. I was glad to met you. Have a nice day)

On 5/25/15, cznic <notifications@github.com> wrote:
> Thank you very much @sitano for your contribution. Please test and please
> don't hesitate to report any (other) problem(s).
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/cznic/ql/issues/99#issuecomment-105227888


-- 


All the best,

Ivan Prisyaznyy (Иван Присяжный),

Backend Everything,


Kaliningrad, Russia,

+79097757255


john.koepi@gmail.com

skype john.koepi1


twitter https://twitter.com/JohnKoepi

github https://github.com/sitano

linkedin cv https://ru.linkedin.com/in/prisyaznyy/

blog http://sitano.github.io/
